### NUMPY

In [1]:
import numpy as np

In [4]:
#numpy is like an array of number
a=np.array([1,2,3])
print(type(a), a.shape, a[1])
a[0]=10# reading or writing
print(a)

<class 'numpy.ndarray'> (3,) 2
[10  2  3]


In [9]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
#[:,:]

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
print(b[0,0],b[1,1])

1 5


In [12]:
n1=np.zeros((2,2))
print(n1)

[[0. 0.]
 [0. 0.]]


In [14]:
n2=np.ones((1,2))
print(n2)

[[1. 1.]]


In [16]:
n3=np.full((2,2),7)
print(n3)

[[7 7]
 [7 7]]


In [19]:
n4=np.eye(3)
print(n4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
num4=np.random.random((2,2))
print(num4)

[[0.25280486 0.45535266]
 [0.68978752 0.82855071]]


In [23]:
any_var=b[1,:2]

In [24]:
print(any_var)

[4 5]
